version: '3'

networks:
  app:
    driver: bridge
  nginx-proxy:
    external: true
services:
    app:
        build:
          context: .
          dockerfile: docker/app/Dockerfile
          args:
            - ENV_FILE=.env.dev
        image: ${APP_IMAGE}
        container_name: mobile-tyres-front-app
        restart: ${DK_RESTART}
        logging:
          driver: 'json-file'
          options:
            max-file: '5'
            max-size: '100m'
        networks:
          - app
    nginx:
        build:
          context: .
          dockerfile: docker/nginx/Dockerfile
          args:
            - APP_IMAGE=${APP_IMAGE}
        image: ${NGINX_IMAGE}
        container_name: mobile-tyres-front-nginx
        logging:
          driver: 'json-file'
          options:
            max-file: '5'
            max-size: '100m'
        restart: ${DK_RESTART}
        networks:
          - app
          - nginx-proxy
        depends_on:
          - app
        environment:
          API_HOST: http://mobile-tyres-api-nginx
          ADMIN_HOST: http://mobile-tyres-admin
          VIRTUAL_HOST: mobile-tyres.dev.glob-com.ru
          LETSENCRYPT_HOST: mobile-tyres.dev.glob-com.ru
          LETSENCRYPT_EMAIL: sites.globcom@yandex.ru
          VIRTUAL_PORT: 80

